config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "nobel_prize/index"
  resources :weekly_sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    # Override the following Devise controllers with our custom versions
    sessions: "users/sessions"
  }

  # use devise_scope if you want custom routes to access devise controllers
  # here root path is accessing devise controller
  devise_scope :user do
    root to: "users/sessions#new"
  end

  resources :users, only: %i[show index edit update]
  resources :notifications
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  validates :title, :body, presence: true
  #
  # TODO: Distinguish different actions
  #
  # after_create_commit :send_notification('create')
  # after_update_commit :send_notification('update')
  # after_destroy_commit :send_notification('destroy')
  #
  #   def send_notification(status)
  #     NotificationRelayJob.perform_later(self, status)
  #   end
  #
  after_commit -> { NotificationRelayJob.perform_later(self) }
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.order("created_at desc").limit(20)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to notifications_path, notice: "notification was successfully created." }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(notification_params)
        format.html { redirect_to @notification, notice: "notification was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  private

    def notification_params
      params.require(:notification).permit(:title, :body)
    end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with model: notification, local: true do |form| %>
  <%= tag.div class: 'form-body' do%>
    <%= tag.h4 class: 'form-section' do %>
      <%= add_icon('icon-head')%>  Details
    <% end %>
    <%= tag.div class: 'row' do %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :title, 'Title' %>
          <%= form.text_field :title, id: :title, class: 'form-control', placeholder: 'Subject' %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= tag.div class: 'form-group' do%>
    <%= form.label :body, 'Body' %>
    <%= form.text_area :body, id: :body, class: 'form-control', placeholder: 'About Notification', rows: 5 %>
  <% end %>
  <%= tag.div class: 'form-actions' do%>
    <%= form.button type: 'reset', class: 'btn btn-warning mr-1' do %><%= add_icon('icon-cross2')%> Cancel<% end %>
    <%= form.button type: 'submit', class: 'btn btn-primary' do %><%= add_icon('icon-cross2')%> Save<% end %>
  <% end %>
<% end %>

app/views/notifications/_navbar_notifications.html.erb
<%= link_to notifications_path, class: 'list-group-item' do%>
  <%= tag.div class: 'media' do %>
    <%= tag.div class: 'media-left valign-middle' do %>
      <%= add_icon('icon-cart3 icon-bg-circle bg-cyan') %>
    <% end %>
    <%= tag.div class: 'media-body' do %>
      <%= tag.h6 notification.title, class: 'media-heading' %>
      <%= tag.p notification.body, class: 'notification-text font-small-3 text-muted' %>
      <%= tag.small do%>
        <%= tag.time '30 minutes ago', class: 'media-meta text-muted'%>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/notifications/create.html.erb
<h1>Notifications#create</h1>
<p>Find me in app/views/notifications/create.html.erb</p>

app/views/notifications/destroy.html.erb
<h1>Notifications#destroy</h1>
<p>Find me in app/views/notifications/destroy.html.erb</p>

app/views/notifications/edit.html.erb
<h1>Notifications#edit</h1>
<p>Find me in app/views/notifications/edit.html.erb</p>

app/views/notifications/index.html.erb
<div class="app-content content container-fluid">
  <div class="content-wrapper">
    <div class="content-header row">
      <div class="content-header-left col-md-6 col-xs-12 mb-1">
        <h2 class="content-header-title">Notifications</h2>
      </div>
      <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
        <div class="breadcrumb-wrapper col-xs-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to 'Home', root_path%>
            </li>
            <li class="breadcrumb-item"><%= link_to 'Notifications', notifications_path%>
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="content-body"><!-- Basic ListGroups start -->
      <section id="basic-listgroup">
        <div class="row match-height">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">Recent</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                  <ul class="list-inline mb-0">
                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                    <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                  </ul>
                </div>
              </div>
              <div class="card-body collapse in">
                <div class="card-block">
                  <p>You have following notifications</p>
                  <ul class="list-group">
                    <% @notifications.each do |notification| %>
                      <li class="list-group-item">
                        <h5 class="list-group-item-heading"><%=notification.title%></h5>
                        <p class="list-group-item-text"><%=notification.body%></p>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/notifications/new.html.erb
<div class="app-content content container-fluid">
  <div class="content-wrapper">
    <div class="content-header row">
      <div class="content-header-left col-md-6 col-xs-12 mb-1">
        <h2 class="content-header-title">Notifications</h2>
      </div>
      <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
        <div class="breadcrumb-wrapper col-xs-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to 'Home', root_path%>
            </li>
            <li class="breadcrumb-item"><%= link_to 'Notifications', notifications_path%>
            </li>
            <li class="breadcrumb-item"><%= link_to 'Compose', new_notification_path%>
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="content-body"><!-- Basic ListGroups start -->
      <section id="basic-listgroup">
        <div class="row match-height">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">Add new</h4>
              </div>
              <div class="card-body collapse in">
                <div class="card-block">
                  <div class="card-text">
                    <p>Notifications will be broadcasted to all users instantly.</p>
                  </div>
                    <%= render partial: "form", locals: { notification: @notification} %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>