config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "nobel_prize/index"
  resources :weekly_sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    # Override the following Devise controllers with our custom versions
    sessions: "users/sessions"
  }

  # use devise_scope if you want custom routes to access devise controllers
  # here root path is accessing devise controller
  devise_scope :user do
    root to: "users/sessions#new"
  end

  resources :users, only: %i[show index edit update]
  resources :notifications
end

app/models/weekly_sale.rb
# frozen_string_literal: true

class WeeklySale < ApplicationRecord
  has_many_attached :daily_sale_sheets
  validates :sale, :rent, :cost, :gross_profit, :net_profit, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1_000_000 }
end

app/controllers/weekly_sales_controller.rb
# frozen_string_literal: true

class WeeklySalesController < ApplicationController
  before_action :set_weekly_sale, only: %i[show edit update destroy]

  # GET /weekly_sales
  # GET /weekly_sales.json
  def index
    @weekly_sales = WeeklySale.all
  end

  # GET /weekly_sales/1
  # GET /weekly_sales/1.json
  def show
    @weekly_sale = WeeklySale.find(params[:id])
  end

  # GET /weekly_sales/new
  def new
    @weekly_sale = WeeklySale.new
  end

  # GET /weekly_sales/1/edit
  def edit
  end

  # POST /weekly_sales
  # POST /weekly_sales.json
  def create
    @weekly_sale = WeeklySale.new(weekly_sale_params)
    daily_sale_sheets = params[:weekly_sale][:daily_sale_sheets]
    respond_to do |format|
      if @weekly_sale.save
        if daily_sale_sheets
          @weekly_sale.daily_sale_sheets.attach(daily_sale_sheets)
        end
        format.html { redirect_to weekly_sales_path, notice: "Weekly sale was successfully created." }
        format.json { render :show, status: :created, location: @weekly_sale }
      else
        format.html { render :new }
        format.json { render json: @weekly_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekly_sales/1
  # PATCH/PUT /weekly_sales/1.json
  def update
    respond_to do |format|
      if @weekly_sale.update(weekly_sale_params)
        format.html { redirect_to @weekly_sale, notice: "Weekly sale was successfully updated." }
        format.json { render :show, status: :ok, location: @weekly_sale }
      else
        format.html { render :edit }
        format.json { render json: @weekly_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_sales/1
  # DELETE /weekly_sales/1.json
  def destroy
    @weekly_sale.destroy
    respond_to do |format|
      format.html { redirect_to weekly_sales_url, notice: "Weekly sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekly_sale
      @weekly_sale = WeeklySale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weekly_sale_params
      params.fetch(:weekly_sale, {}).permit(:start_date, :end_date, :sale, :rent, :cost, :gross_profit, :net_profit, :daily_sale_sheets)
    end

    def daily_sale_sheet_params
      params.dig(:weekly_sale, :daily_sale_sheets)
  end
end

app/views/weekly_sales/_form.html.erb
<%= form_with model: weekly_sale, local: true do |form| %>
  <% if weekly_sale.errors.any? %>
    <%= tag.div "#{pluralize(weekly_sale.errors.count, "error")} occured.", id: 'total_errors' ,class: 'alert alert-danger mb-2', role: 'alert'%>
    <% weekly_sale.errors.full_messages.each do |message| %>
        <%= tag.div message, class: 'alert alert-danger mb-2', role: 'alert'%>
      <% end %>
  <% end %>
  <%= tag.div class: 'form-body' do%>
    <%= tag.h4 class: 'form-section' do %>
      <%= add_icon('icon-head')%>  Details
    <% end %>
    <%= tag.div class: 'row' do %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :start_date, 'Start Date' %>
          <%= form.text_field :start_date, id: :weekly_sale_start_date, class: 'form-control', placeholder: 'Week start date', type: 'date' %>
        <% end %>
      <% end %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :end_date, 'End Date' %>
          <%= form.text_field :end_date, id: :weekly_sale_end_date, class: 'form-control', placeholder: 'Week end date', type: 'date' %>
        <% end %>
      <% end %>
    <% end %>
    <%= tag.div class: 'row' do %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :sale, 'Total sale' %>
            <%= tag.div class: 'input-group' do %>
              <%= tag.span '£', class: 'input-group-addon' %>
              <%= form.text_field :sale, id: :weekly_sale_sale, class: 'form-control square', placeholder: 'Total sale amount (£)', 'aria-label': 'Amount (to the nearest currency)' %>
              <%= tag.span '.00', class: 'input-group-addon' %>
            <% end %>
        <% end %>
      <% end %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :rent, 'Rent' %>
            <%= tag.div class: 'input-group' do %>
              <%= tag.span '£', class: 'input-group-addon' %>
              <%= form.text_field :rent, id: :weekly_sale_rent, class: 'form-control square', placeholder: 'Weekly Rent', 'aria-label': 'Amount (to the nearest currency)' %>
              <%= tag.span '.00', class: 'input-group-addon' %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
    <%= tag.div class: 'row' do %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :gross_profit, 'Gross Profit' %>
            <%= tag.div class: 'input-group' do %>
              <%= tag.span '£', class: 'input-group-addon' %>
              <%= form.text_field :gross_profit, id: :weekly_sale_gross_profit, class: 'form-control square', placeholder: 'Weekly Gross Profit', 'aria-label': 'Amount (to the nearest currency)' %>
              <%= tag.span '.00', class: 'input-group-addon' %>
            <% end %>
        <% end %>
      <% end %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :net_profit, 'Net Profit' %>
            <%= tag.div class: 'input-group' do %>
              <%= tag.span '£', class: 'input-group-addon' %>
              <%= form.text_field :net_profit, id: :weekly_sale_net_profit, class: 'form-control square', placeholder: 'Weekly Net Profit', 'aria-label': 'Amount (to the nearest currency)' %>
              <%= tag.span '.00', class: 'input-group-addon' %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
    <%= tag.div class: 'row' do %>
      <%= tag.div class: 'col-md-6' do %>
        <%= tag.div class: 'form-group' do%>
          <%= form.label :cost, 'Product Cost' %>
            <%= tag.div class: 'input-group' do %>
              <%= tag.span '£', class: 'input-group-addon' %>
              <%= form.text_field :cost, id: :weekly_sale_cost, class: 'form-control square', placeholder: 'Cost amount (£)', 'aria-label': 'Amount (to the nearest currency)' %>
              <%= tag.span '.00', class: 'input-group-addon' %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
    <% if true %>
    <%= tag.div class: 'form-group' do%>
      <%= form.label :daily_sale_sheets, 'Uplaod daily sale sheets' %>
      <%= form.file_field :daily_sale_sheets, id: :daily_sale_sheets, multiple: true, class: 'form-control' %>
    <% end %>
  <% end %>
  <% end %>
  <%= tag.div class: 'form-actions' do%>
    <%= form.button type: 'reset', class: 'btn btn-warning mr-1' do %><%= add_icon('icon-cross2')%> Cancel<% end %>
    <%= form.button type: 'submit', class: 'btn btn-primary' do %><%= add_icon('icon-cross2')%> Create Weekly sale<% end %>
  <% end %>
<% end %>

app/views/weekly_sales/edit.html.erb
<h1>Editing Weekly Sale</h1>

<%= render 'form', weekly_sale: @weekly_sale %>

<%= link_to 'Show', @weekly_sale %> |
<%= link_to 'Back', weekly_sales_path %>

app/views/weekly_sales/index.html.erb
<div class="app-content content container-fluid">
  <div class="content-wrapper">
    <div class="content-header row">
      <div class="content-header-left col-md-6 col-xs-12 mb-1">
        <h2 class="content-header-title">Cash Register</h2>
      </div>
      <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
        <div class="breadcrumb-wrapper col-xs-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to 'Home', root_path%>
            </li>
            <li class="breadcrumb-item"><%= link_to 'Cash Register', weekly_sales_path%>
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="content-body">
      <section id="basic-listgroup">
        <div class="row match-height">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">List all sales</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                  <ul class="list-inline mb-0">
                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                    <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                  </ul>
                </div>
              </div>
              <div class="card-body collapse in">
                <div class="card-block">
                  <p>You have following sales</p>
                  <ul class="list-group">
                    <% @weekly_sales.each do |weekly_sale| %>
                      <li class="list-group-item">
                        <h5 class="list-group-item-heading"><%= weekly_sale.start_date %> - <%= weekly_sale.end_date %></h5>
                        <p class="list-group-item-text"><%= weekly_sale.sale %></p>
                        <p class="list-group-item-text"><%= weekly_sale.rent %></p>
                        <p class="list-group-item-text"><%= weekly_sale.cost %></p>
                        <p class="list-group-item-text"><%= weekly_sale.gross_profit %></p>
                        <p class="list-group-item-text"><%= weekly_sale.net_profit %></p>
                        <p class="list-group-item-text">
                          <strong>Documents:</strong>
                          <ul>
                            <% weekly_sale.daily_sale_sheets.each do |daily_sale_sheet| %>
                              <li><%= link_to daily_sale_sheet.blob.filename, url_for(daily_sale_sheet), target: 'blank' %></li>
                            <% end %>
                          </ul>
                        </p>

                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/weekly_sales/new.html.erb
<div class="app-content content container-fluid">
  <div class="content-wrapper">
    <div class="content-header row">
      <div class="content-header-left col-md-6 col-xs-12 mb-1">
        <h2 class="content-header-title">Cash Register</h2>
      </div>
      <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
        <div class="breadcrumb-wrapper col-xs-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to 'Home', root_path%>
            </li>
            <li class="breadcrumb-item"><%= link_to 'Cash Register', weekly_sales_path%>
            </li>
            <li class="breadcrumb-item"><%= link_to 'Add Sales', new_weekly_sale_path%>
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="content-body"><!-- Basic ListGroups start -->
      <section id="basic-listgroup">
        <div class="row match-height">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">Add Weekly Sales</h4>
              </div>
              <div class="card-body collapse in">
                <div class="card-block">
                  <div class="card-text">
                    <p>Weekly sales data.</p>
                  </div>
                    <%= render 'form', weekly_sale: @weekly_sale %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/weekly_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @weekly_sale.start_date %>
</p>



<p>
  <strong>End date:</strong>
  <%= @weekly_sale.end_date %>
</p>



<p>
  <strong>Sales:</strong>
  <%= @weekly_sale.sale %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @weekly_sale.rent %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @weekly_sale.cost %>
</p>

<p>
  <strong>Gross profit:</strong>
  <%= @weekly_sale.gross_profit %>
</p>

<p>
  <strong>Net profit:</strong>
  <%= @weekly_sale.net_profit %>
</p>

<%= link_to 'Edit', edit_weekly_sale_path(@weekly_sale) %> |
<%= link_to 'Back', weekly_sales_path %>